### ISSUE TITLE
Some Material Icons render weird on windows 10

### ISSUE THREAD

**Issue by maxmedina05** [google/material-design-icons#1034]
OS: Windows 10 Pro (x64) 10.0.18362 Build 18362
Browser: Chrome v83.0.4103.116 (64-Bit)

Some icons look very different on windows to how they look on MacOS or Linux.
The ones that spotted are the following:

- list
- timeline
- dynamic_feed
- directions_railway
- local_fire_department

![image](https://user-images.githubusercontent.com/6037236/87138490-c8efc700-c29e-11ea-9d48-2d2fa21192f9.png)

**Comment by thuyet-pham-tr** [comment]
This issue seems oddly specific to Windows 10 (works fine on macOS). I was able to verify using a variety of browsers.
* Chrome  85.0.4183.102 (64-bit)
* Microsoft Edge 44.17763.831.0
* Firefox 80.0.1 (64-bit)

I also noticed a few other icons that seemed to have the same issue.
* info_outline
* system_update_alt

**Comment by thescientist13** [comment]
@maxmedina05 
Did you see the [`v4.0.0`](https://github.com/google/material-design-icons/releases/tag/4.0.0) release by chance?  It has updated icons.  🤞    

Our team is going to try those out and see if it resolves the issue.  (bonus is now these assets can come from npm! 🎉 )

**Comment by henrydaggett** [comment]
Problem still persists in v4, but seems to be limited just to the sharp icon variants.

![4F945EFA-32C8-41F1-8D3A-13694958A7EB](https://user-images.githubusercontent.com/34757031/95191089-2a550280-07c8-11eb-9426-ad18c4146994.png)

**Comment by ilyakonrad** [comment]
Facing this issue with round icons as well (group, timeline, list, local_fire_department).

Windows 10 Enterprise, 1703, 15063.296
Chrome 87.0.4280.88

![image](https://user-images.githubusercontent.com/25200186/101177606-ad6fc900-3650-11eb-8a4f-e35cb406b092.png)

**Comment by RoelN** [comment]
Confirmed on Windows 10 in Chrome 87 and Edge 87. Should be fixed in the font production process.

**Comment by SBDMattGump** [comment]
Chrome: Version 88.0.4324.146
Windows 10 Enterprise: Version 1809

Wanted to specifically call out the Sharp `list` icon as well. 

<img width="1105" alt="Screen Shot 2021-02-04 at 12 09 08 PM" src="https://user-images.githubusercontent.com/5400448/106928991-d0b30500-66e1-11eb-9c75-08dc800b1faa.png">

**Comment by RamonvdW** [comment]
The problem with the semi-transparent icons is still present in the rounded icon set.
Affected are: list, timeline, directions_railway, local_fire_department.

Visible on: Windows 10, Chrome 89.0. Hardware accelleration disabled.
No visible on: Linux Debian 10, Chrome 89.0

Not sure if the "live fonts" provided by static.google.com and visible on https://material.io/resources/icons/?icon=list&style=round are actually the same as present in this repository.

**Comment by tphinney** [comment]
Is this all better now? Should definitely be better for the variable font, but hoping that the static (non-variable) fonts are good now as well.

**Comment by RamonvdW** [comment]
I checked https://material.io/resources/icons/?icon=list&style=round
and the problem is still showing (Win10, Chrome 100.0.4896.127)
Is the site showing the latest?

![Schermafbeelding 2022-04-28 144218](https://user-images.githubusercontent.com/50547870/165754494-53d8862a-02fd-434d-9157-f22c57a614ae.png)

**Comment by tphinney** [comment]
I believe this is being caused by duplicated sets of outlines. That is, in the produced TTF (and almost certainly in the SVG source upstream from it), the full set of outlines is duplicated and overlaid on top of itself. Very likely this is the case in the SVG source, but causes no problems there.

For fonts, in *some* font rasterizing environments this does not cause problems (macOS, iOS), but in some it is a Very Bad Thing indeed.

The good news is, we can test for this in an automated fashion, ID any and all such glyphs in the 4 fonts, and then fix them. In fact, it looks like my buddy Vassil has already got a check for this as part of another script that is doing something else (in producing fancy variable-font glyphs), we can pull out and repurpose that big of code...

**Comment by tphinney** [comment]
Note that this is NOT a problem in Material Symbols, just Material Icons.

Checked for duplicated contours, and came up with this list of likely problem glyphs across the various fonts, which includes almosta all the glyphs discussed previously in this thread (except /group)

Regular:
uniF1B0 (do_not_touch)
uniF1C1 (smart_button)

Outlined:
dynamic_feed
input
list
rounded_corner
slow_motion_video
smart_button
swap_vert
system_update_alt

Round:
directions_railway
list
local_fire_department
rounded_corner
timeline

Sharp:
dynamic_feed
info_outline
input
link
list
rounded_corner
slow_motion_video
system_update_alt
tab
timeline
toc

Two-Tone:
_13mp
dynamic_feed
hourglass_bottom
hourglass_top
kitchen
list
medication_liquid
rounded_corner
smart_button

**Comment by tphinney** [comment]
@EsoFromTheEast So, I believe the problem is duplicated contours in the SVG source files for the specified glyphs. Is this something you can address, or is it upstream from you? I think even a text editor could be used for this purpose, given that we are talking about deleting entire contours it is not too complex. But there are ~ 30 glyphs to be fixed.
