### ISSUE TITLE
notes icon webfont issue

### ISSUE THREAD

**Issue by GitStorageOne** [google/material-design-icons#807]
With Web Fonts css code like below, i get same icon as presented at material.io/tools/icons
```
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
<i class="material-icons">notes</i>
```
![notes](https://user-images.githubusercontent.com/3978064/41349901-ff2bbe94-6f19-11e8-9822-360c8b5acc8f.PNG) (correct icon)

But with self hosted fonts (sources from "./iconfont/" folder), i get different icon:

![notes_wrong](https://user-images.githubusercontent.com/3978064/41350066-8a668da4-6f1a-11e8-8abe-cd55b5dbcb6a.PNG) (wrong icon)

Seems file ".\iconfont\MaterialIcons-Regular.woff2" is outdated.
As well as other font files.

**Comment by RoelN** [comment]
The assets have been updated since this issue was reported, so I believe this should be fixed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by Alllle** [comment]
Still have the same problem. Same icon when trying to use notes

**Comment by RoelN** [comment]
@Alllle Please use the fonts in https://github.com/google/material-design-icons/tree/master/font or as served by Google Fonts, they will show the correct icon.
