### ISSUE TITLE
If lang is not set to en, icon will not be centered in Firefox

### ISSUE THREAD

**Issue by Sun79** [google/material-design-icons#956]
![](https://s2.ax1x.com/2019/08/30/mXxRns.png)
Firefox version: 68.0.2x64
System version: Windows 10 1803
CodePen link: https://codepen.io/sun79/pen/xxKLxBp

**Comment by Landius** [comment]
same in firefox 78.01

**Comment by RoelN** [comment]
I can't replicate this anymore. Both the font and the browsers have had significant updates in the mean time (specifically, the font has been updated to 4.0.0).

Closing this issue because I believe it has been addressed. If not, feel free to reopen this issue or create a new one with more information.

**Comment by austinw-fineart** [comment]
Still reproducible as of Firefox 85.0

1. Go to https://material-components.github.io/material-components-web-catalog/#/component/drawer
2. Open Inspector
3. Change lang attribute to "zh"
4. The drawer icon shifts upwards

**Comment by RoelN** [comment]
I tried on Firefox 85 and 86 on Windows 10, following your instructions, but still cannot reproduce this.

I'll reopen the issue so someone on the Google team can have a closer look.

**Comment by tphinney** [comment]
I know this is ancient, from years ago, but I wanted to follow up nonetheless, in case it is still a problem. Going to that URL today, and attempting “inspection” from Firefox yields an empty box, no CSS/HTML at all. (Although it works just fine on other sites/resources.) So while I have a theory, I have no easy way to test it.

IF the problem is still happening, please read on. If not, please close the issue!

Here is my theory as to what might have been going wrong. They issue claims “if lang is not set to en”—but I wonder if it is in fact specifically *only* if lang is set to zh or jp or some other ideographic writing system, with which they routinely do a baseline adjustment for English. If the icon is being treated as English text, then it could shift as part of an automatic baseline adjustment for matching English to Chinese/Japanese/etc.

The amount of the shift also seems consistent with this theory.

Now, seeing as these fonts lack a 'BASE' table, they are not providing any direct instruction to the layout engine about such baseline shifting. That said, it might be that the fact that the OS/2 table has a bit setting on that says they support “basic Latin” characters is enough to cause this problem.

Now by sheer coincidence, it happens that in exploring a possible fix to another issue, I just this past weekend built a variant set of Material Symbols fonts (the variable-font versions of the icons) that turn off that specific bit! I would be happy to provide that for testing, if @Sun79 is still around and cares about this today.

**Comment by austinw-fineart** [comment]
At the very least, I can confirm that the problem still exists. And yes, it occurs when I set the lang to zh or jp.

**Comment by tphinney** [comment]
I was really asking about the opposite: does it occur when you set the lang to a non-ideographic language. For example, Arabic (ar) or Hebrew (he)?

**Comment by austinw-fineart** [comment]
It does not occur with ar or he.

**Comment by tphinney** [comment]
Aha, OK, that is very useful information.

So, let’s talk about this behavior vs desired behavior.

In general use, if you have a given vertical offset for the icons to get the alignment you want compared to some western language (English or any Latin language, Greek, or even Cyrillic), and you change the language to Japanese or Chinese, you would also be changing the text to Japanese or Chinese, right?

So, what I _suspect_ Firefox is doing, is shifting text in other writing systems (notably Latin/Greek/Cyrillic), when you change the body to Chinese or Japanese. The amount it is doing that is based on the normal amount you would have to shift Latin/Greek/Cyrillic to align with an ideographic language. From memory I think the default for some other apps that do this sort of thing might be 20%, so let’s say that is the amount, for now.

Is this a Firefox-only thing, other browsers are not doing it?

If it is happening in all browsers....
So, _if you have already aligned your icons so they match up with your Latin (or Greek or Cyrillic) starting font,_ and you switch to Japanese at the same point size (or your alignment was based on the em and not points/px), the browsers will probably be doing a decent job of _still aligning_. That is probably good—as long as it is consistent across browsers.

If it is Firefox only? Damn. I believe we *could* “defeat” this behavior. Add a 'base' table and specifically say “make no adjustments for aligning with Chinese and Japanese.”

**Comment by austinw-fineart** [comment]
It only occurs in Firefox; Chromium browsers are perfectly fine.
In fact, the problem is quite old now: https://bugzilla.mozilla.org/show_bug.cgi?id=1280900

**Comment by tphinney** [comment]
Thanks! All very helpful. 
Assuming that Firefox respects the 'base' table that might do the trick. Will give it a try—likely some time this week—to find out.

From the Mozilla bug entry, this seems to affect other icon fonts as well — probably our new Material Symbols variable fonts are affected too. Although of course this bug report dates back long before they shipped.

**Comment by tphinney** [comment]
Actually, come to think of it, if the behavior *is* desirable but needs to be cross-browser, adding a 'base' table that _has_ an explicit shift could also fix the problem—by getting the same behavior across browsers. We could instead of suppressing the behavior on Firefox, get it on all browsers, if that is better.

**Comment by tphinney** [comment]
I've built a set of experimental fonts, taking the existing OTF and TTF Material Icons fonts, and adding a 'BASE' table with explicit offsets.

If @austinw-fineart or any previous commenters would like to play with them, I’d be happy to make them available privately for a test… I think this will likely get consistent behavior from other browsers as well as Firefox.

**Comment by tphinney** [comment]
Could also use the 'BASE' table to completely suppress the behavior, I should think.
